GEMINI_API_KEY = "AIzaSyCJizjDXZ6EKmbX3RJXyfe4BSpIikbiNnA"
SUPABASE_URL = "https://kkivuvzmevmbgxmgqtfg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtraXZ1dnptZXZtYmd4bWdxdGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzAxMzMsImV4cCI6MjA3NTQwNjEzM30.MyG0GKUCUZ6MsNYIqjNFaCKo_qmbpOgSRQ4NTDwZhKQ"
